### ISSUE TITLE
Implement GetCompositeSchedule request

### ISSUE THREAD

**Issue by c-jimenez** [c-jimenez/open-ocpp#1]
Implement GetCompositeSchedule request : 

Ask for the non-ocpp charging constraints schedule of the user application through the IOcppEventHandler interface in the form of an OCPP ChargingProfile data structure.
Compute composite schedule with received OCPP charging profiles and user application charging profile is any.

**Comment by rmadhuraj** [comment]
Hi, what challenges stopped you implementing this ??

**Comment by c-jimenez** [comment]
Hi,
I'm just looking for a nice and efficient way to implement it.
And since I thought this wasn't a very usefull request, I just put this request in the backlog comparing to testing and improving the core of the stack's implementation.
My target is to have it implemented in the 1.0.0 version that I hope to release around january 2023.

If you have some implementation suggestion, don't hesitate to share, this will make the 1.0.0 release sooner!

**Comment by rmadhuraj** [comment]
Ok sure, I just started looking into your implementation. Built the code and ran the quick_start_cs and quick_start_cp examples, i see some communication happening , periodic heart beat exchange,

How to test the unit test cases https://github.com/c-jimenez/open-ocpp/tree/develop/tests/chargepoint ?

**Comment by c-jimenez** [comment]
These are ctests so 2 options:

- From the main makefile : make gcc-unit-tests
- From the generated makefile in the build directory : make tests
