### ISSUE TITLE
StopTransaction.req json messgae without field reason will lead to crash

### ISSUE THREAD

**Issue by MarkJlMa** [c-jimenez/open-ocpp#109]
Within method StopTransactionReqConverter::fromJson,
data.reason = ReasonHelper.fromString(json["reason"].GetString()) doesn't check if the message contains [reason] memeber.

**Comment by c-jimenez** [comment]
Thanks, the reason field was not marked as optional in the StopTransactionReq struct.
A fix will come shortly in the develop branch.
