### ISSUE TITLE
[Core profile] RemoteStartTransaction on unknown connector id

### ISSUE THREAD

**Issue by SiarheiVolkau** [c-jimenez/open-ocpp#121]
The OCPP 1.6 states that:
> ... When no connector id is provided, the Charge Point is in control of the connector selection. ...

However, `TransactionManager::handleMessage` says that:
> // No remote start allowed without connector id

Is there a way to implement connector selection in user code?
Could, at least, the message propagate to the `remoteStopTransactionRequested` handler with no connector id?

**Comment by c-jimenez** [comment]
Hello,
Yes this is indeed a problem. I will fix it so that the user callback can be called in this case.

**Comment by SiarheiVolkau** [comment]
Thank you so much!
Don't forget about `DefaultChargePointEventsHandler::remoteStartTransactionRequested` now it can crash on connector id 0.
