### ISSUE TITLE
To get charging schedules;

### ISSUE THREAD

**Issue by Monika-18mis** [c-jimenez/open-ocpp#157]
Hi,
How can I get the charging schedule from the communication of open-ocpp?

Thanks.

**Comment by c-jimenez** [comment]
Hi,
What do you mean by getting the charging schedule?
If it is by the mean f the OCPP protocol, you can send a GetCompositeSchedule request to your charging station to get the applicable charging schedules.
It is from you charging station application to retrieve the received charging schedule, their is no API yet for that. The only available API is getSetpoint() to retrieve the actual setpoint to apply given the received charging schedules.

**Comment by Monika-18mis** [comment]
Yes, Where Can I request GetCompositeSchedule, as I am making communication between quick_start_centralsystem and quick_start_chargepoint.

**Comment by c-jimenez** [comment]
Hi,

Sorry for the delay, I totally missed your second question :(
The GetComposite schedule can be asked using the charge point proxy object.

For instance in the quick_start_centralsystem example application, you can add this code after line 124 :

```
auto chargepoint = iter_chargepoint.second->proxy();

 ocpp::types::Optional<unsigned int> schedule_connector_id;
 ocpp::types::Optional<ocpp::types::DateTime> schedule_start;
 ocpp::types::Optional<ocpp::types::ChargingSchedule> schedule;
chargepoint->getCompositeSchedule(1u, 60s, schedule_connector_id, schedule_start, schedule);
```
