### ISSUE TITLE
connectorId=0 on RemoteStartTransaction should be rejected

### ISSUE THREAD

**Issue by Habbus** [c-jimenez/open-ocpp#161]
Hi, 
We are working on some testing against the ocpp1.6 spec and noticed the following issue. 
The RemoteStartTransaction.req has an optional connectorId. Currently, the TransactionManager treats an unset optional as connectorid=0.  However, the ocpp1.6 standard states the following on the connectorId field:

> Optional. Number of the connector on which to start the transaction.
  connectorId SHALL be > 0

Our test case expects a status of Rejected in the RemoteStartTransaction.conf. The spec specifically states that connectorId should be larger than 0.

Would you be fine with changing the logic so the RemoteStartTransaction.req is Rejected when connectorId is set and equal to 0?

**Comment by Habbus** [comment]
If you agree I'm also fine with opening a PR myself, but first I'd like to hear what you think.

**Comment by c-jimenez** [comment]
Hi,

Yes you're right it is a mistake regarding to the standard to handle both cases in the same way.
You can open a PR for this fix.

Thanks for your feedback.
