### ISSUE TITLE
request from chargepoint to central system

### ISSUE THREAD

**Issue by smdkhalifa7** [c-jimenez/open-ocpp#172]
I've observed that when charge point is connected to central system, Central system is sending requests regards some operations to charge point and the regarding functions are getting triggered and sending back the response to central system.
but what I've to know is whether the charge point can send request to central system from itself without being called from central system, As I've to use DATA TRANSFER  operation from both sides (i.e, central system to charge point and charge point to central system).
so, it is possible to send data transfer from charge point to central system ? If yes, how ?

**Comment by c-jimenez** [comment]
Hi,

Yes you can initiate messages from the charge point side.
If you take a look at the quick_charge_point example you will see that you can use the charge point object created here :

`std::unique_ptr<IChargePoint> charge_point = IChargePoint::create(config.stackConfig(), config.ocppConfig(), event_handler);`

The `IChargePoint` interface allow to send all the messaes defined in the OCPP standard => https://github.com/c-jimenez/open-ocpp/blob/develop/src/chargepoint/interface/IChargePoint.h

Regards.
