### ISSUE TITLE
Plug and Charge support

### ISSUE THREAD

**Issue by ruudvd** [c-jimenez/open-ocpp#83]
First thank you for this amazing project!

Are there plans to support the ISO15118 / Plug and Charge as mentioned here: https://www.openchargealliance.org/uploads/files/ocpp_1_6_ISO_15118_v10.pdf ?

**Comment by c-jimenez** [comment]
Thanks for your interest in this project.

The ISO15118 support was not planned yet.
Sadly I won't have the time to take a look at this before the start of 2023 but I think this will be the next major feature. Maybe someone could help me on this subject to start the implementations earlier.

First target for now is to release a version 1.0 with the very few missing features of the standard 1.6 protocol.

**Comment by c-jimenez** [comment]
> Are there plans to support the ISO15118 / Plug and Charge as mentioned here: https://www.openchargealliance.org/uploads/files/ocpp_1_6_ISO_15118_v10.pdf ?

Hi,

I took a look at the white paper and it appeared that it was not much work.
So the implementation is now ready in the develop branch if you want to test it and will be officially released by the en of the year in the 1.0 release.

Regards

**Comment by ruudvd** [comment]
> > Are there plans to support the ISO15118 / Plug and Charge as mentioned here: https://www.openchargealliance.org/uploads/files/ocpp_1_6_ISO_15118_v10.pdf ?
> 
> Hi,
> 
> I took a look at the white paper and it appeared that it was not much work. So the implementation is now ready in the develop branch if you want to test it and will be officially released by the en of the year in the 1.0 release.
> 
> Regards

Nice! at the moment i don't have the hardware to test it (yet).
