### ISSUE TITLE
Some CONFIGURATION_VALUES that leads to time intervals Negative values are not allowed.

### ISSUE THREAD

**Issue by mahdidadashi65** [c-jimenez/open-ocpp#96]
for CONFIGURATION_VALUES that related to to time intervals ,Negative values are not allowed. ChangeConfiguration is expected to return a REJECTED result.
for Test Case Id: 040_2 chargepoint will return rejected but return accepted.

**Comment by c-jimenez** [comment]
Hi,
The range of the configuration values is not checked by the OpenOCPP stack.
It is the responsibility of  the user application to check this through the [Configuration Interface](https://github.com/c-jimenez/open-ocpp#configuration-interface).
In the examples, this interface has been developed without worrying about values ranges to have a quick running example.
